title: Rafael Torres
author: Rafael Torres
email: rafaelmtorres@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a web version of my resume, here you can find more about what I do, my previous work experiences and interests. 
# social links
github_username:  rafaelmtorres # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-cayman 
